# Generated by Django 4.1.7 on 2023-02-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Список задач", max_length=100)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="Статус задачи"),
                ),
                (
                    "start",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Время начала задания"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, help_text="Время выполнения задания", null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
